name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      DJANGO_SETTINGS_MODULE: config.settings

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run --source=. -m pytest
        coverage report
